INSERT INTO Categories(categoryName) VALUES ('Dam'), ('Herr')

INSERT INTO SubCategories(categoryId, subCategoryName) VALUES (1, 'Jeans'), (1,'Klänningar'), (1, 'Sko'), (2, 'Byxor'), (2, 'Skjortor'), (2, 'Sko') 

INSERT INTO Products(productName, supplierId, subCategoryId, [description], unitPrice, unitInStock, size, color) VALUES ('Regular fit oxfordskjorta', 5, 5, 'Vår bästsäljande oxfordskjorta. Skjortan har en normal passform och button down-krage, locker loop och boxpleat i ryggen samt vår klassisk sköldlogotyp broderad på bröstet.', 500, 10, 'M', 'Vit'), ('Vintage Slim High Ankle Jeans', 1, 1, 'Ett par ankellånga 5-ficksjeans i tvättad denim. Jeansen har extra hög midja och smala ben. Jeansen är delvis tillverkade av återvunnen bomull.', 299, 15, '36', 'Denimblå'), ('Nike Metcon 7', 2, 3, 'Nike Metcon 7 håller högsta standard när det kommer till styrketräning och är till och med mer slitstark och stabil än sina föregångare. Vi har också lagt till React-skummaterial som gör skon bekvämare och gör dig redo för högintensiv konditionsträning. Dessutom fixerar en flik skosnörena så att de inte knyts upp medan du fokuserar på ditt nästa personbästa.', 1449, 5, '39', 'Rosa'), ('Ribbstickad klänning', 1, 2, 'En vadlång, figurnära klänning i fint ribbstickad kvalitet. Klänningen har krage och v-ringning fram samt lång ärm. Slits bak. Ofodrad.', 299, 10, 'M', 'Ljusbeige'), ('H&M+ Skjortklänning', 1, 2, 'En vadlång klänning i jacquardvävd kvalitet. Klänningen har krage och knäppning fram samt nedhasad axel och lång ärm med manschett som har slits. Hög slits i sidorna. Ofodrad.', 249, 5, 'L', 'Svart'), ('90s Baggy High Jeans', 1, 1, 'Ett par hellånga 5-ficksjeans i stadig, tvättad denim. Jeansen har hög midja och lös passform med raka ben. Gylf med dragkedja och knapp.', 299, 8, '38', 'Ljus denimblå'), ('Mom Loose-fit Ultra High Jeans', 1, 1, 'Ett par ankellånga 5-ficksjeans i tvättad denim. Jeansen har lös passform och raka, lätt avsmalnande ben. Extra hög midja. Gylf med dragkedja och knapp. Bomullen i jeansen är delvis återvunnen.', 199, 8, '40', 'Svart'), ('Finstickade sneakers', 1, 3, 'Ett par finstickade sneakers med resårkant upptill och hälla i ripsband bak. Innersula i mesh. Grov yttersula med mönstrad undersida. Sulhöjd 5 cm.', 249, 12, '37', 'Svart'), ('Chelseaboots i läder', 1, 3, 'Ett par chelseaboots i mjukt läder med resår längs med båda sidorna av skaftet. Foder i ekologisk bomullskvalitet och innersula i läder. Klackhöjd 5 cm.', 899, 10, '38', 'Svart'), ('Slacks Relaxed Fit', 1, 4, 'Ett par slacks i vävd kvalitet med pressveck. Slacksen har linning med dold hyska och hake. Sidfickor och passpoalfickor bak. Gylf med dragkedja och knapp. Relaxed Fit – en avslappnad passform med god rörelsevidd. Detta skapar en bekväm och ledig silhuett.', 399, 5, '32', 'Beige'), ('Joggers i bomull Relaxed Fit', 1, 4, 'Blank Staples är en tidlös kollektion av minimalistiska streetwear-plagg av hög kvalitet. Dessa joggers är tillverkade i kraftig, 460 gsm sweatshirtkvalitet av bomull. De har en avslappnad passform för en bekväm stil och ledig silhuett. ', 299, 18, 'M', 'Ljus gråmelerad')
	

INSERT INTO PostalCodes(city, postalCode, country) VALUES ('Stockholm', '106 38', 'Sweden'),('Solna', '169 56', 'Sweden'),('Stockholm', '111 53', 'Sweden'), ('Stockholm', '114 32', 'Sweden'), ('Stockholm', '115 56', 'Sweden')

INSERT INTO Payments(paymentType) VALUES ('Visa'), ('Mastercard'),('PayPal')

INSERT INTO Shipments(companyName, freight) VALUES ('DHL', 49), ('Postnord', 69),('Bring', 29)


INSERT INTO Suppliers([name], [address], phone, postalCodeId) VALUES 
('H & M Hennes & Mauritz Sverige AB','Mäster Samuelsgatan 46', '08 796 55 00',1), ('Nike Sweden AB','Dalvägen 16','08 444 70 00',2),('JD Sports Fashion Sweden AB','Hamngatan 37','08 465 018 45', 3), ('Hugo Boss Scandinavia AB','Engelbrektsgatan 9-11 ','08 611 42 41',4), ('Gant AB','Tullvaktsvägen 9','08 506 76 00',5)

INSERT INTO SubCategories(categoryId, subCategoryName) VALUES (1, 'Jeans'), (1,'Klänningar'), (1, 'Sko'), (2, 'Byxor'), (2, 'Skjortor'), (2, 'Sko') 